Add work and about-us sections
umarahgul/PortfolioMicroverse pull request #3
Opened 2023-06-07 14:22 UTC by umarahgul

This Pull request would be putting forward, two more milestones of the mobile-first website constituting portfolio updates. It has two main sections of "works" constituting projects built by the portfolio holder and "About us", this high lights the languages, skills and frameworks utilized in creating these projects. This also updates a client to what to expect when deciding to work with the owner of the portfolio.

2023-06-07 21:02 UTC, sheezu900 commented on index.html
> +            </div>
remove this div

2023-06-07 21:03 UTC, sheezu900 commented on index.html
> +            </div>
remove this div

2023-06-07 21:03 UTC, shahzaman900 commented on index.html
> +            </div>
remove this div

2023-06-07 23:23 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @umarahgul  :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:
- [ ] I kindly request that you adhere to the Figma design provided for your project. The Figma design serves as a visual reference and guideline for implementing the desired user interface and overall look of your application. Please ensure that the implemented code aligns with the design specifications provided in Figma. This includes aspects such as layout, color scheme, typography, and any other visual elements defined in the design.

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 23:23 UTC, Cabraham1 commented on styles.css
> +  height: 1263px;
- [ ] Nice work so far but I kindly suggest you remove the height style from the About section as it tends to add unnecessary white space below your application

2023-06-07 23:23 UTC, Cabraham1 commented on index.html
> +            </ul>
- [ ] Nice work so far 👍🏿 but i notice you are using a` button `inside the `ul li` i kidly suggest you remove the `button `, as per project requirement it should just be a `ul li`
 - [ ] I also notice your design dose not aling with the figmaa design

 - [ ] your design
 
![image](https://github.com/umarahgul/PortfolioMicroverse/assets/68823331/fca90e1d-68b4-45ac-a342-57de303f92f5)

 - [ ] Figm Design

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/68823331/65457cdc-258d-4efa-a6c1-dc77ae32796c)

- [ ] I kindly suggest you stick onto the figms drsign  provided 😉

2023-06-07 23:23 UTC, Cabraham1 commented on index.html
> +            </ul>
- [ ] Nice work so far 👍🏿 but i notice you are using a` button `inside the `ul li` i kidly suggest you remove the `button `, as per project requirement it should just be a `ul li`
 - [ ] I also notice your design dose not aling with the figmaa design

 - [ ] your design
 
![image](https://github.com/umarahgul/PortfolioMicroverse/assets/68823331/fca90e1d-68b4-45ac-a342-57de303f92f5)

 - [ ] Figm Design

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/68823331/65457cdc-258d-4efa-a6c1-dc77ae32796c)

- [ ] I kindly suggest you stick onto the figms drsign  provided 😉

2023-06-07 23:23 UTC, Cabraham1 commented on index.html
> +            </ul>
- [ ] Nice work so far 👍🏿 but i notice you are using a` button `inside the `ul li` i kidly suggest you remove the `button `, as per project requirement it should just be a `ul li`
 - [ ] I also notice your design dose not aling with the figmaa design

 - [ ] your design
 
![image](https://github.com/umarahgul/PortfolioMicroverse/assets/68823331/fca90e1d-68b4-45ac-a342-57de303f92f5)

 - [ ] Figm Design

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/68823331/65457cdc-258d-4efa-a6c1-dc77ae32796c)

- [ ] I kindly suggest you stick onto the figms drsign  provided 😉

2023-06-08 17:59 UTC, frank1738 requested changes
Hi @umarahgul , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 17:59 UTC, ghost commented on index.html
> +            <ul class="stack">
- [ ] Good work up to this point but there are some aspects you can improve on.
  -  Kindly adjust the padding around this specific project card as the button appears to touch the borderline. It would be better to adjust the position of the text header of all the project cards to be at the start and not at the center as provided in the Figma template

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/98453979/70ae3be4-f5a0-433d-a2da-228f19d25ca4)

2023-06-08 17:59 UTC, ghost commented on index.html
> +            feature or website. Look through some of my work and experience!
- [ ] The same case applies to your about me content. Kindly adjust the elements to be at the start and not at the center

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/98453979/7b809db6-1905-4254-990f-5dc3084019d8)

### Check out the original, design

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/98453979/06e7e4bc-60a9-4d98-a209-60ea195a0a20)

2023-06-08 17:59 UTC, ghost commented on index.html
> +            <li><a href="#"><img src="images/medium.png" /></a></li>
- [ ] Your language section is missing some key icons and elements provided in the original design. Kindly add them to improve the aesthetic aspect of this section.

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/98453979/27f626cd-d205-40b8-a55c-0c05a5a07a1c)

### Checkout the original design

![image](https://github.com/umarahgul/PortfolioMicroverse/assets/98453979/99ffe46a-d0b9-42ee-bd07-a2b20fec7b9e)

2023-06-08 22:10 UTC, algerina approved these changes
Hi @umarahgul ,

Great job so far! 

May I highlight the following: 
- [x] Your app looks awesome👏  ✔️ 
- [x] You implemented all the required changes by the previous TSE's✔️ 



## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-06-08 22:10 UTC, algerina commented on index.html
> +              </div>
- [ Optional] Well done adding the languages as a dropdown menu however, you have to stick to the Figma design as much as possible.

2023-06-09 17:39 UTC, merged